name: wallpaper_by_prince
description: WALLPAPER BY PRINCE - Dark Premium Wallpapers & Live
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cached_network_image: ^3.3.1
  provider: ^6.0.0
  path_provider: ^2.0.0
  sqflite: ^2.0.0
  gallery_saver: ^2.3.2
  video_player: ^2.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/live/
    
